name: SimpleParkour
main: me.shadow5353.simpleparkour.SimpleParkour
version: 1.0.1
description: A simple parkour plugin

commands:
    parkour:
        usage: /<command> <argument>
        aliases: [p]